export const FEATURES = [
  { n:'Four-level C4 drill-down',        cat:'Presentation', key:'L1/ENGINE',        d:'Click a rectangle to drill in, right-click/Esc to go back; the navigation stack guarantees you can always return to L1' },
  { n:'Hover a port for its fields',     cat:'Presentation', key:'L3-TEMPLATE/RET',  d:'A structured message expands into a [field, type, meaning] table' },
  { n:'Hover a row for its source',      cat:'Presentation', key:'L3-TEMPLATE/CODE', d:'Snippets are cut fresh from disk; the key is file:line, so symbols sharing a name never collide' },
  { n:'Drawer viewport and scrolling',   cat:'Presentation', key:'L1/ENGINE',        d:'A file with hundreds of exports still cannot stretch its rectangle to thousands of pixels' },
  { n:'Scenario flow playback',          cat:'Presentation', key:'L3-TEMPLATE/FLOW', d:'Projected across levels — the same path reads at a different granularity at L1 than at L4' },
  { n:'Six language families',           cat:'Inventory',    key:'L2-TOOL/SCAN',     d:'TS/JS · Vue/Svelte single-file components · Python · Go · Rust · JVM, all sharing one kind vocabulary' },
  { n:'Directory summary drives blocks', cat:'Inventory',    key:'L1/SCAN',          d:'Printed descending by symbol count; over 80 means split again' },
  { n:'Full coverage, no duplication',   cat:'Quality gate', key:'L2-TOOL/BUILD',    d:'Duplicate assignment within a diagram, or any repository file left out, fails the build on the spot' },
  { n:'Independent back-to-source check',cat:'Quality gate', key:'L2-GATE/BACKREF',  d:'The checker reuses none of the extractor\'s regexes and does not read its output; they share only "what counts as a source file"' },
  { n:'Statistics filled automatically', cat:'Quality gate', key:'L2-TOOL/BUILD',    d:'{{files}}/{{lines}}/{{exports}} come from what the blockmap really assigns — a hand-written aggregate gets past every assertion' },
  { n:'No blind spot in coverage',       cat:'Quality gate', key:'L2-TOOL/LANG',     d:'Scan and check share the file-set definition, ruling out the silent gap where "scan knows it and verify does not"' },
  { n:'Instant path-pattern check',      cat:'Inventory',    key:'L2-TOOL/STATS',    d:'Matching zero files raises a warning — putting that pattern in blockmap is a coverage hole' },
  { n:'Stubbed smoke test',              cat:'Quality gate', key:'L2-GATE/STUB',     d:'Proves the engine neither throws nor produces a NaN layout, with no real browser involved' },
];
