export const FLOWS = [
  {
    name:'一次完整的生成',
    from:'SKILL.md 的五步工作流',
    role:'控制流：手写语义、机读清单，两者只在 build 汇合',
    steps:[
      ['L1/CLAUDE',        '读源码，想清楚每个模块的输入输出实际装着什么'],
      ['L1/SCAN',          'scan.mjs 全扫源码根，抽出每个文件的导出符号与行号'],
      ['L2-TOOL/SCAN',     '六族语言的声明匹配 + 种类精化；结尾报出未识别扩展名与超标文件'],
      ['L2-TOOL/STATS',    '按 blockmap 同款模式核一遍每块到底命中几个文件'],
      ['L1/CLAUDE',        '照目录汇总设计分块 —— 每块符号数 ≤80'],
      ['L3-TEMPLATE/DIA',  '写 diagrams.mjs：图、块、端口五元组'],
      ['L3-TEMPLATE/MAP',  '写 blockmap.mjs：目录 → 文件，全覆盖不重复；它也决定占位符的统计口径'],
      ['L3-TEMPLATE/RET',  '写 ret.mjs：结构化端口展开字段表'],
      ['L3-TEMPLATE/CODE', '写 code.mjs：只挑符号，片段交给 build 现切'],
      ['L1/BUILD',         'build.mjs 装配；重复归属、未覆盖、占位符填不上都会当场失败'],
      ['L1/ENGINE',        '引擎原样拼到数据段之后'],
      ['L1/HTML',          '单文件 HTML 落地'],
      ['L2-TOOL/LANG',     '重扫用的是与 scan 同一套文件集合定义 —— 否则覆盖率会有盲区'],
      ['L2-GATE/REDERIVE', 'verify 独立重扫磁盘，算反向覆盖率'],
      ['L2-GATE/BACKREF',  '每个符号回它声称的 文件:行号 上对质'],
      ['L2-GATE/TRAVERSE', 'smoke 逐图布局绘制，拦下 NaN 布局'],
      ['L1/GATE',          '8 类断言 0 失败 + 冒烟通过，才算做完'],
      ['L1/CLAUDE',        '只报 HTML 路径，不产出任何其他文件'],
    ],
  },
  {
    name:'清单为什么不会漂',
    from:'verify.mjs 的设计约束',
    role:'数据流：把「准确」变成可执行的断言，而不是承诺',
    steps:[
      ['L1/SCAN',          '清单只有一个来源：直读磁盘'],
      ['L1/CLAUDE',        '人不碰清单 —— 人只写语义'],
      ['L1/BUILD',         '片段由 build 按真实行号现切，不经人手'],
      ['L2-GATE/REDERIVE', '核对器不读 inventory.json，自己重扫一遍'],
      ['L2-GATE/BACKREF',  '不复用抽取器的正则，自己读原文件那一行'],
      ['L2-GATE/SNIPPET',  '片段逐行比对'],
      ['L1/GATE',          '于是「准确」不是两个同源程序互相点头'],
    ],
  },
];
