export const FLOWS = [
  {
    name:'One complete generation',
    from:'the five-step workflow in SKILL.md',
    role:'control flow: hand-written semantics, machine-read inventories, meeting only at build',
    steps:[
      ['L1/CLAUDE',        'Read the source; work out what each module\'s inputs and outputs actually carry'],
      ['L1/SCAN',          'scan.mjs sweeps the source roots, extracting every file\'s exported symbols and line numbers'],
      ['L2-TOOL/SCAN',     'Declaration matching for six language families + kind refinement; it ends by reporting unrecognized extensions and oversized files'],
      ['L2-TOOL/STATS',    'Check with blockmap\'s own patterns how many files each block would actually match'],
      ['L1/CLAUDE',        'Design the partitioning from the directory summary — at most 80 symbols per block'],
      ['L3-TEMPLATE/DIA',  'Write diagrams.mjs: diagrams, blocks, five-part ports'],
      ['L3-TEMPLATE/MAP',  'Write blockmap.mjs: directory → files, full coverage without duplication; it also sets what the placeholders count'],
      ['L3-TEMPLATE/RET',  'Write ret.mjs: expand the structured ports into field tables'],
      ['L3-TEMPLATE/CODE', 'Write code.mjs: pick the symbols only; build cuts the snippets fresh'],
      ['L1/BUILD',         'build.mjs assembles; duplicate assignment, uncovered files and unfillable placeholders all fail on the spot'],
      ['L1/ENGINE',        'The engine is concatenated verbatim after the data section'],
      ['L1/HTML',          'The single-file HTML lands'],
      ['L2-TOOL/LANG',     'The rescan uses the same file-set definition as scan — otherwise coverage would have a blind spot'],
      ['L2-GATE/REDERIVE', 'verify rescans the disk independently and computes reverse coverage'],
      ['L2-GATE/BACKREF',  'Every symbol is confronted at the file:line it claims'],
      ['L2-GATE/TRAVERSE', 'smoke lays out and draws every diagram, catching NaN layouts'],
      ['L1/GATE',          '8 assertion classes at zero failures plus a passing smoke test is what "done" means'],
      ['L1/CLAUDE',        'Report only the HTML path; produce no other file'],
    ],
  },
  {
    name:'Why the inventories cannot drift',
    from:'the design constraints of verify.mjs',
    role:'data flow: turning "accurate" into executable assertions instead of a promise',
    steps:[
      ['L1/SCAN',          'The inventory has exactly one source: reading the disk'],
      ['L1/CLAUDE',        'A person never touches the inventory — a person writes only semantics'],
      ['L1/BUILD',         'Snippets are cut by build at the real line numbers, never passing through human hands'],
      ['L2-GATE/REDERIVE', 'The checker does not read inventory.json; it rescans for itself'],
      ['L2-GATE/BACKREF',  'It reuses none of the extractor\'s regexes; it reads that line of the original file itself'],
      ['L2-GATE/SNIPPET',  'Snippets are compared line by line'],
      ['L1/GATE',          'So "accurate" is not two programs from the same source nodding at each other'],
    ],
  },
];
